package ctrmap.editor.gui.workspace;

import xstandard.gui.file.XFileDialog;
import ctrmap.formats.common.GameInfo;
import xstandard.fs.accessors.DiskFile;
import ctrmap.editor.system.workspace.GameDetector;
import xstandard.fs.FSFile;
import xstandard.gui.components.listeners.DocumentAdapterEx;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;

public class AddGameDialog extends javax.swing.JDialog {

	private final List<OnGameAddSuccessListener> listeners = new ArrayList<>();
	private final List<CanAddGameVerifier> verifiers = new ArrayList<>();

	public AddGameDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);

		pathField.getDocument().addDocumentListener(new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				btnConfirm.setEnabled(!pathField.getText().trim().isEmpty());
			}
		});
	}

	public void addOnGameAddSuccessListener(OnGameAddSuccessListener l) {
		listeners.add(l);
	}
	
	public void addCanAddGameVerifier(CanAddGameVerifier v) {
		verifiers.add(v);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathLabel = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a game directory");
        setResizable(false);

        pathLabel.setText("Extracted game data root path");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathLabel)
                        .addGap(0, 234, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		String gamePath = pathField.getText();
		FSFile gameRoot = new DiskFile(gamePath);
		if (gameRoot.exists()) {
			for (CanAddGameVerifier v : verifiers) {
				if (!v.verifyGamePath(gamePath)) {
					return;
				}
			}
			GameInfo.Game game = GameDetector.detectGameType(gameRoot);
			if (game == null) {
				JOptionPane.showMessageDialog(this, "The given path is not a recognizable Pokémon game dump", "Invalid path", JOptionPane.ERROR_MESSAGE);
			} else {
				for (OnGameAddSuccessListener l : listeners) {
					l.onGameAdded(gamePath);
				}
				dispose();
			}
		} else {
			JOptionPane.showMessageDialog(this, "The given path does not exist", "Invalid path", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
		String path = pathField.getText();
		FSFile select = XFileDialog.openDirectoryDialog("Select a game dump location", (path == null || path.trim().isEmpty()) ? null : new DiskFile(pathField.getText()));
		if (select != null) {
			pathField.setText(select.getPath());
		}
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    // End of variables declaration//GEN-END:variables
}
