package ctrmap.editor.gui.workspace;

import ctrmap.editor.system.juliet.CTRMapPluginDatabase;

public class PluginEntryUI extends javax.swing.JPanel {

	final CTRMapPluginDatabase.PluginEntry plugin;
	private final ProjectManager mgr;
	
	public PluginEntryUI(CTRMapPluginDatabase.PluginEntry plugin, ProjectManager mgr) {
		initComponents();
		this.plugin = plugin;
		this.mgr = mgr;
		nameLabel.setText(plugin.name);
		nameLabel.setToolTipText(plugin.path);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        btnRemovePlugin = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));
        setAlignmentY(0.0F);
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        nameLabel.setText("Plugin JAR name");
        add(nameLabel, java.awt.BorderLayout.CENTER);

        btnRemovePlugin.setText("Uninstall");
        btnRemovePlugin.setMinimumSize(new java.awt.Dimension(80, 15));
        btnRemovePlugin.setPreferredSize(new java.awt.Dimension(80, 15));
        btnRemovePlugin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePluginActionPerformed(evt);
            }
        });
        add(btnRemovePlugin, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemovePluginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePluginActionPerformed
		mgr.removePluginEntryAction(this);
    }//GEN-LAST:event_btnRemovePluginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemovePlugin;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
