package ctrmap.editor.gui.workspace;

import ctrmap.editor.system.workspace.ProjectRegistryData;

public class ProjectEntryUI extends javax.swing.JPanel {

	public ProjectRegistryData.ProjectRegistryEntry e;
	private ProjectManager man;
	
	public ProjectEntryUI(ProjectRegistryData.ProjectRegistryEntry e, ProjectManager man) {
		initComponents();
		this.e = e;
		this.man = man;
		nameLabel.setText(e.projectName + " - " + e.projectDataPath);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnOpenProject = new javax.swing.JButton();
        btnRemoveProject = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));
        setAlignmentY(0.0F);
        setLayout(new java.awt.BorderLayout());

        nameLabel.setText("Project Name");
        add(nameLabel, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(130, 15));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnOpenProject.setText("Open");
        btnOpenProject.setPreferredSize(new java.awt.Dimension(59, 15));
        btnOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenProjectActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenProject, java.awt.BorderLayout.CENTER);

        btnRemoveProject.setText("Remove");
        btnRemoveProject.setPreferredSize(new java.awt.Dimension(71, 15));
        btnRemoveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProjectActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveProject, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProjectActionPerformed
		man.removeProjectEntryAction(this);
    }//GEN-LAST:event_btnRemoveProjectActionPerformed

    private void btnOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenProjectActionPerformed
		man.launchCTRMapForEntryAction(this);
    }//GEN-LAST:event_btnOpenProjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenProject;
    private javax.swing.JButton btnRemoveProject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
