package ctrmap.editor.gui;

import xstandard.gui.DialogUtils;
import ctrmap.util.CMPrefs;

public class ControlsHelpDialog extends javax.swing.JFrame {

	private static final String CONTROLS_HELP_DIALOG_REGNODE = "ControlsHelpDialog";
	private static final String CONTROLS_HELP_GUARDIAN_REGBOOL_KEY = "FriendlyControlsHelpGuardianNotified1.0";

	/**
	 * Creates new form ControlsHelpDialog
	 */
	public ControlsHelpDialog() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        btnF5 = new javax.swing.JButton();
        lblF5 = new javax.swing.JLabel();
        btnCtrlSCtrl = new javax.swing.JButton();
        btnCtrlSS = new javax.swing.JButton();
        lblCtrlS = new javax.swing.JLabel();
        btnCtrlPCtrl = new javax.swing.JButton();
        btnCtrlPP = new javax.swing.JButton();
        lblCtrlP = new javax.swing.JLabel();
        btnCtrlECtrl = new javax.swing.JButton();
        btnCtrlEE = new javax.swing.JButton();
        lblCtrlE = new javax.swing.JLabel();
        editorsPanel = new javax.swing.JPanel();
        btnF2 = new javax.swing.JButton();
        lblF2 = new javax.swing.JLabel();
        btnF3 = new javax.swing.JButton();
        lblF3 = new javax.swing.JLabel();
        mcPanel = new javax.swing.JPanel();
        btnShift = new javax.swing.JButton();
        lblShift = new javax.swing.JLabel();
        btnW = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        lblPlayerMove = new javax.swing.JLabel();
        mcSep1 = new javax.swing.JSeparator();
        btnCtrl = new javax.swing.JButton();
        lblCtrl = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        lblC = new javax.swing.JLabel();
        lblWarnGen5UseWtw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("CONTROLS");

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Main"));

        btnF5.setText("F5");

        lblF5.setText("Toggle Mission Control");

        btnCtrlSCtrl.setText("Ctrl");

        btnCtrlSS.setText("S");

        lblCtrlS.setText("Save");

        btnCtrlPCtrl.setText("Ctrl");

        btnCtrlPP.setText("P");

        lblCtrlP.setText("Pack workspace");

        btnCtrlECtrl.setText("Ctrl");

        btnCtrlEE.setText("E");

        lblCtrlE.setText("Export ROM");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblF5))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnCtrlSCtrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCtrlSS)
                        .addGap(18, 18, 18)
                        .addComponent(lblCtrlS))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnCtrlPCtrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCtrlPP)
                        .addGap(18, 18, 18)
                        .addComponent(lblCtrlP))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnCtrlECtrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCtrlEE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCtrlE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF5)
                    .addComponent(lblF5))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtrlSCtrl)
                    .addComponent(btnCtrlSS)
                    .addComponent(lblCtrlS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtrlPCtrl)
                    .addComponent(btnCtrlPP)
                    .addComponent(lblCtrlP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtrlECtrl)
                    .addComponent(btnCtrlEE)
                    .addComponent(lblCtrlE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Editors"));

        btnF2.setText("F2");

        lblF2.setText("Switch to Orthogonal camera");

        btnF3.setText("F3");

        lblF3.setText("Switch to Perspective camera");

        javax.swing.GroupLayout editorsPanelLayout = new javax.swing.GroupLayout(editorsPanel);
        editorsPanel.setLayout(editorsPanelLayout);
        editorsPanelLayout.setHorizontalGroup(
            editorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editorsPanelLayout.createSequentialGroup()
                        .addComponent(btnF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblF2))
                    .addGroup(editorsPanelLayout.createSequentialGroup()
                        .addComponent(btnF3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblF3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editorsPanelLayout.setVerticalGroup(
            editorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF2)
                    .addComponent(lblF2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF3)
                    .addComponent(lblF3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mcPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mission Control"));

        btnShift.setText("SHIFT");

        lblShift.setText("Walk through walls");

        btnW.setText("W");

        btnS.setText("S");

        btnA.setText("A");

        btnD.setText("D");

        lblPlayerMove.setText("Player movement:");

        btnCtrl.setText("CTRL");

        lblCtrl.setText("L button - toggle walk/run default");

        btnC.setText("C");

        lblC.setText("B button - [HOLD] toggle walk/run");

        lblWarnGen5UseWtw.setForeground(new java.awt.Color(255, 0, 0));
        lblWarnGen5UseWtw.setText("(required for Gen 5 at the moment!)");

        javax.swing.GroupLayout mcPanelLayout = new javax.swing.GroupLayout(mcPanel);
        mcPanel.setLayout(mcPanelLayout);
        mcPanelLayout.setHorizontalGroup(
            mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mcPanelLayout.createSequentialGroup()
                        .addComponent(lblPlayerMove)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mcPanelLayout.createSequentialGroup()
                        .addComponent(btnShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarnGen5UseWtw)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mcPanelLayout.createSequentialGroup()
                        .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCtrl)
                            .addComponent(btnC))
                        .addGap(18, 18, 18)
                        .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC)
                            .addComponent(lblCtrl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mcSep1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mcPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mcPanelLayout.setVerticalGroup(
            mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayerMove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnS)
                    .addComponent(btnA)
                    .addComponent(btnD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShift)
                    .addComponent(lblShift)
                    .addComponent(lblWarnGen5UseWtw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mcSep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtrl)
                    .addComponent(lblCtrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC)
                    .addComponent(lblC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editorsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		if (!CMPrefs.node(CONTROLS_HELP_DIALOG_REGNODE).getBoolean(CONTROLS_HELP_GUARDIAN_REGBOOL_KEY, false)) {
			if (DialogUtils.showYesNoDialog(this, "Red alert!", "Did you read the text in red?")) {
				CMPrefs.node(CONTROLS_HELP_DIALOG_REGNODE).putBoolean(CONTROLS_HELP_GUARDIAN_REGBOOL_KEY, true);
				DialogUtils.showInfoMessage(this, "Thank you.", "Nice! I promise never to bother you again.\nThis is your friendly controls help guardian, signing off.");
			} else {
				DialogUtils.showInfoMessage(this, "Seriously man...", "Alright. We've got time. Read it, mkay?\nSincerely, the friendly controls help guardian.");
				return;
			}
		}
		dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCtrl;
    private javax.swing.JButton btnCtrlECtrl;
    private javax.swing.JButton btnCtrlEE;
    private javax.swing.JButton btnCtrlPCtrl;
    private javax.swing.JButton btnCtrlPP;
    private javax.swing.JButton btnCtrlSCtrl;
    private javax.swing.JButton btnCtrlSS;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnF2;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnShift;
    private javax.swing.JButton btnW;
    private javax.swing.JPanel editorsPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCtrl;
    private javax.swing.JLabel lblCtrlE;
    private javax.swing.JLabel lblCtrlP;
    private javax.swing.JLabel lblCtrlS;
    private javax.swing.JLabel lblF2;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblPlayerMove;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblWarnGen5UseWtw;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mcPanel;
    private javax.swing.JSeparator mcSep1;
    // End of variables declaration//GEN-END:variables
}
