package ctrmap.creativestudio.dialogs;

import ctrmap.renderer.scene.animation.AbstractAnimation;
import xstandard.gui.DialogOptionRemember;
import java.util.ArrayList;
import java.util.List;

public class AnimeSelectionPanel extends javax.swing.JPanel {

	private List<AbstractAnimation> animations = new ArrayList<>();

	public AnimeSelectionPanel() {
		initComponents();
	}

	public void loadAnimations(List<AbstractAnimation> animations) {
		anmBox.removeAllItems();
		if (animations != null) {
			this.animations = animations;
			for (AbstractAnimation m : animations) {
				anmBox.addItem(m.name);
			}
		}
	}

	public List<AbstractAnimation> getAllAnimations() {
		return animations;
	}
	
	public AbstractAnimation getSelectedAnimation() {
		int index = anmBox.getSelectedIndex();
		if (index == -1 || index >= animations.size()) {
			return null;
		}
		return animations.get(index);
	}
	
	public boolean hasAnyModel() {
		return anmBox.getItemCount() > 0;
	}

	public void setAnmBoxEnabled(boolean value) {
		anmBox.setEnabled(value);
	}
	
	public void saveComboBoxValue(String key) {
		DialogOptionRemember.putRememberedComboBox(key, anmBox);
	}
	
	public void restoreComboBoxValue(String key) {
		DialogOptionRemember.selectRememberedComboBox(key, anmBox);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anmLabel = new javax.swing.JLabel();
        anmBox = new javax.swing.JComboBox<>();

        anmLabel.setText("Animation:");

        anmBox.setMaximumRowCount(25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(anmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anmBox)
            .addComponent(anmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anmBox;
    private javax.swing.JLabel anmLabel;
    // End of variables declaration//GEN-END:variables
}
