package ctrmap.creativestudio.dialogs;

import xstandard.gui.DialogOptionRemember;
import xstandard.gui.file.ExtensionFilter;

public class BatchExportFormatSelector extends javax.swing.JDialog {

	private ExtensionFilter filters[] = new ExtensionFilter[0];
	private ExtensionFilter result;

	public BatchExportFormatSelector(java.awt.Frame parent, boolean modal, ExtensionFilter... filters) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);

		if (filters != null) {
			this.filters = filters;
			for (ExtensionFilter flt : filters) {
				formatComboBox.addItem(flt.getDisplayText());
			}
			
			DialogOptionRemember.selectRememberedComboBox(makeFilterHash(), formatComboBox);
		}
	}

	private String makeFilterHash() {
		int hash = 31;
		if (filters != null) {
			for (ExtensionFilter f : filters) {
				hash = 7 * hash + f.formatName.hashCode();
			}
		}
		return String.valueOf(hash);
	}

	public ExtensionFilter getResult() {
		return result;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectLabel = new javax.swing.JLabel();
        formatComboBox = new javax.swing.JComboBox<>();
        btnConfirmExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bulk export");
        setResizable(false);

        selectLabel.setText("Select a file format:");

        formatComboBox.setMaximumRowCount(20);

        btnConfirmExport.setText("Export");
        btnConfirmExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectLabel)
                        .addGap(0, 216, Short.MAX_VALUE))
                    .addComponent(formatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmExport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmExport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmExportActionPerformed
		int idx = formatComboBox.getSelectedIndex();
		if (idx >= 0 && idx < filters.length) {
			result = filters[idx];
		} else {
			result = null;
		}
		DialogOptionRemember.putRememberedComboBox(makeFilterHash(), formatComboBox);
		dispose();
    }//GEN-LAST:event_btnConfirmExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmExport;
    private javax.swing.JComboBox<String> formatComboBox;
    private javax.swing.JLabel selectLabel;
    // End of variables declaration//GEN-END:variables
}
