package ctrmap.creativestudio.dialogs;

import ctrmap.renderer.scene.model.Model;
import xstandard.gui.DialogOptionRemember;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;

public class ModelSelectionPanel extends javax.swing.JPanel {

	private List<Model> models = new ArrayList<>();

	public ModelSelectionPanel() {
		initComponents();
	}

	public void loadModels(List<Model> models) {
		modelBox.removeAllItems();
		if (models != null) {
			this.models = models;
			for (Model m : models) {
				modelBox.addItem(m.name);
			}
		}
	}

	public List<Model> getAllModels() {
		return models;
	}
	
	public Model getSelectedModel() {
		int index = modelBox.getSelectedIndex();
		if (index == -1 || index >= models.size()) {
			return null;
		}
		return models.get(index);
	}
	
	public boolean hasAnyModel() {
		return modelBox.getItemCount() > 0;
	}

	public void setModelBoxEnabled(boolean value) {
		modelBox.setEnabled(value);
	}

	public void saveComboBoxValue(String key) {
		DialogOptionRemember.putRememberedComboBox(key, modelBox);
	}
	
	public void restoreComboBoxValue(String key) {
		DialogOptionRemember.selectRememberedComboBox(key, modelBox);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelLabel = new javax.swing.JLabel();
        modelBox = new javax.swing.JComboBox<>();

        modelLabel.setText("Model:");

        modelBox.setMaximumRowCount(25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(modelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modelBox)
            .addComponent(modelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> modelBox;
    private javax.swing.JLabel modelLabel;
    // End of variables declaration//GEN-END:variables
}
