package ctrmap.creativestudio.dialogs;

import ctrmap.renderer.scene.model.Model;
import ctrmap.renderer.scene.model.Skeleton;
import java.util.List;

public class ModelSelectionDialog extends javax.swing.JDialog {

	private Model result;
	
	public ModelSelectionDialog(java.awt.Dialog parent, boolean modal, List<Model> models, boolean skelOnly) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		init(models, skelOnly);
	}
	
	public ModelSelectionDialog(java.awt.Frame parent, boolean modal, List<Model> models, boolean skelOnly) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		init(models, skelOnly);
	}
	
	private void init(List<Model> models, boolean skelOnly) {
		hintLabel.setText(skelOnly ? "This action requires a model skeleton. Please select one:" : "This action requires a model. Please select one:");
		setTitle(skelOnly ? "Select a skeleton" : "Select a model");
		selector.loadModels(models);
	}
	
	public Model getResult() {
		return result;
	}
	
	public Skeleton getResultSkl() {
		if (result != null) {
			return result.skeleton;
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selector = new ctrmap.creativestudio.dialogs.ModelSelectionPanel();
        hintLabel = new javax.swing.JLabel();
        btnConfirmSelection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        hintLabel.setText("This action requires a model skeleton. Please select one:");

        btnConfirmSelection.setText("Select");
        btnConfirmSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmSelection)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmSelection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSelectionActionPerformed
		result = selector.getSelectedModel();
		dispose();
    }//GEN-LAST:event_btnConfirmSelectionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmSelection;
    private javax.swing.JLabel hintLabel;
    private ctrmap.creativestudio.dialogs.ModelSelectionPanel selector;
    // End of variables declaration//GEN-END:variables
}
