package ctrmap.creativestudio.dialogs;

import ctrmap.formats.generic.xobj.OBJExportSettings;
import ctrmap.formats.generic.xobj.OBJFile;
import ctrmap.renderer.scenegraph.G3DResource;
import xstandard.fs.FSFile;
import xstandard.gui.DialogOptionRemember;
import java.io.File;

public class OBJExportDialog extends javax.swing.JDialog {

	private FSFile target;
	private G3DResource source;
	
	public OBJExportDialog(java.awt.Frame parent, boolean modal, G3DResource source, FSFile target) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		this.target = target;
		this.source = source;
		
		DialogOptionRemember.setRememberedCheckbox(btnWriteVCol);
		DialogOptionRemember.setRememberedCheckbox(btnSeparateTex);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeparateTex = new javax.swing.JCheckBox();
        btnWriteVCol = new javax.swing.JCheckBox();
        btnIsVColTrifindo = new javax.swing.JCheckBox();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export OBJ");
        setResizable(false);

        btnSeparateTex.setSelected(true);
        btnSeparateTex.setText("Separate texture directory");

        btnWriteVCol.setSelected(true);
        btnWriteVCol.setText("Write vertex colors");
        btnWriteVCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteVColActionPerformed(evt);
            }
        });

        btnIsVColTrifindo.setText("PDSMS vertex color format");

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIsVColTrifindo)
                    .addComponent(btnWriteVCol)
                    .addComponent(btnSeparateTex))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnSeparateTex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWriteVCol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIsVColTrifindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWriteVColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteVColActionPerformed
		btnIsVColTrifindo.setEnabled(btnWriteVCol.isSelected());
    }//GEN-LAST:event_btnWriteVColActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        DialogOptionRemember.putRememberedCheckbox(btnWriteVCol);
		DialogOptionRemember.putRememberedCheckbox(btnSeparateTex);
		
		new OBJFile(source).write(target, new OBJExportSettings(btnWriteVCol.isSelected(), btnIsVColTrifindo.isSelected(), btnSeparateTex.isSelected()));
		dispose();
    }//GEN-LAST:event_btnExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JCheckBox btnIsVColTrifindo;
    private javax.swing.JCheckBox btnSeparateTex;
    private javax.swing.JCheckBox btnWriteVCol;
    // End of variables declaration//GEN-END:variables
}
