package ctrmap.creativestudio.dialogs;

import ctrmap.renderer.scene.Scene;
import ctrmap.renderer.scene.animation.skeletal.SkeletalAnimation;
import ctrmap.renderer.scene.model.Model;
import ctrmap.renderer.util.camcvt.Skel2CamScalarSource;
import ctrmap.renderer.util.camcvt.Skel2CamVectorSource;
import xstandard.gui.DialogUtils;
import java.util.List;
import javax.swing.JFrame;

public class Skel2CamDialogLookat extends javax.swing.JDialog {

	private boolean confirmed;
	private String camTgtName;
	private Model refModel;
	
	private List<Model> models;
	
	public Skel2CamDialogLookat(java.awt.Frame parent, boolean modal, SkeletalAnimation anm, List<Model> models) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		
		posSource.loadJoints(anm.bones);
		tgtSource.loadJoints(anm.bones);
		camRollSource.loadJoints(anm.bones);
		
		this.models = models;
		for (Model m : models){
			bakeModel.addItem(m.name);
		}
	}
	
	public static boolean checkApplicableOpenDialog(JFrame parent, SkeletalAnimation anm){
		if (anm.bones.isEmpty()){
			DialogUtils.showErrorMessage(parent, "Pointless operation", "This animation does not contain any joint transforms.");
			return false;
		}
		return true;
	}
	
	public boolean getConfirmed(){
		return confirmed;
	}
	
	public String getResultCamName(){
		return camTgtName;
	}

	public Model getRefModel(){
		return refModel;
	}
	
	public Skel2CamVectorSource getCamposSource() {
		return posSource.getVectorSource();
	}
	
	public Skel2CamVectorSource getCamtgtSource() {
		return tgtSource.getVectorSource();
	}
	
	public Skel2CamScalarSource getCamrollSource() {
		return camRollSource.getScalarSource();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camTgtBtnGroup = new javax.swing.ButtonGroup();
        convModeGroup = new javax.swing.ButtonGroup();
        camTgtLabel = new javax.swing.JLabel();
        btnCamNameMatchJoint = new javax.swing.JRadioButton();
        btnCamNameCustom = new javax.swing.JRadioButton();
        btnCamNameCustomField = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        convModeLabel = new javax.swing.JLabel();
        btnConvLocal = new javax.swing.JRadioButton();
        btnConvGlobal = new javax.swing.JRadioButton();
        bakeModelLabel = new javax.swing.JLabel();
        bakeModel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posSource = new ctrmap.creativestudio.dialogs.Skel2CamSourcePanel();
        jLabel3 = new javax.swing.JLabel();
        tgtSource = new ctrmap.creativestudio.dialogs.Skel2CamSourcePanel();
        jLabel4 = new javax.swing.JLabel();
        camRollSource = new ctrmap.creativestudio.dialogs.Skel2CamSourcePanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Skeletal To Camera");
        setResizable(false);

        camTgtLabel.setText("Target camera name:");

        camTgtBtnGroup.add(btnCamNameMatchJoint);
        btnCamNameMatchJoint.setSelected(true);
        btnCamNameMatchJoint.setText("Same as camera position joint's name");
        btnCamNameMatchJoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamNameMatchJointActionPerformed(evt);
            }
        });

        camTgtBtnGroup.add(btnCamNameCustom);
        btnCamNameCustom.setText("Custom");
        btnCamNameCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamNameCustomActionPerformed(evt);
            }
        });

        btnCamNameCustomField.setEnabled(false);

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        convModeLabel.setText("Conversion mode:");

        convModeGroup.add(btnConvLocal);
        btnConvLocal.setSelected(true);
        btnConvLocal.setText("Local (direct)");
        btnConvLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvLocalActionPerformed(evt);
            }
        });

        convModeGroup.add(btnConvGlobal);
        btnConvGlobal.setText("Global (baked)");
        btnConvGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvGlobalActionPerformed(evt);
            }
        });

        bakeModelLabel.setText("Model:");

        bakeModel.setMaximumRowCount(25);
        bakeModel.setEnabled(false);

        jLabel1.setText("Sources:");

        jLabel2.setText("Camera position");

        posSource.setIsVector(true);

        jLabel3.setText("Target position");

        tgtSource.setIsVector(true);

        jLabel4.setText("Camera roll");

        camRollSource.setIsVector(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConvert)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(bakeModelLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bakeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnConvGlobal)
                                            .addComponent(btnConvLocal)))
                                    .addComponent(convModeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(camTgtLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCamNameCustom)
                                            .addComponent(btnCamNameMatchJoint)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(btnCamNameCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(posSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(15, 15, 15)
                                                .addComponent(tgtSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(33, 33, 33)
                                                .addComponent(camRollSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(posSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tgtSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(camRollSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(convModeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConvLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConvGlobal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bakeModelLabel)
                            .addComponent(bakeModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(camTgtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCamNameMatchJoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCamNameCustom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCamNameCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
		confirmed = true;
		refModel = (Model)Scene.getNamedObject((String)bakeModel.getSelectedItem(), models);
		if (btnConvLocal.isSelected()){
			refModel = null;
		}
		String camTgt = btnCamNameCustom.isSelected() ? btnCamNameCustomField.getText() : posSource.getVectorSource().jntName;
		if (camTgt == null || camTgt.isEmpty()){
			DialogUtils.showErrorMessage(this, "Input error", "Camera name can not be empty");
			return;
		}
		camTgtName = camTgt;
		dispose();
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnCamNameMatchJointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamNameMatchJointActionPerformed
		btnCamNameCustomField.setEnabled(false);
    }//GEN-LAST:event_btnCamNameMatchJointActionPerformed

    private void btnCamNameCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamNameCustomActionPerformed
		btnCamNameCustomField.setEnabled(true);
    }//GEN-LAST:event_btnCamNameCustomActionPerformed

    private void btnConvLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvLocalActionPerformed
		bakeModel.setEnabled(false);
    }//GEN-LAST:event_btnConvLocalActionPerformed

    private void btnConvGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvGlobalActionPerformed
		if (bakeModel.getItemCount() == 0){
			DialogUtils.showErrorMessage("No model", "Can not bake global transforms without a model in the scene.");
			btnConvLocal.setSelected(true);
		}
		else {
			bakeModel.setEnabled(true);
		}
    }//GEN-LAST:event_btnConvGlobalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bakeModel;
    private javax.swing.JLabel bakeModelLabel;
    private javax.swing.JRadioButton btnCamNameCustom;
    private javax.swing.JTextField btnCamNameCustomField;
    private javax.swing.JRadioButton btnCamNameMatchJoint;
    private javax.swing.JButton btnCancel;
    private javax.swing.JRadioButton btnConvGlobal;
    private javax.swing.JRadioButton btnConvLocal;
    private javax.swing.JButton btnConvert;
    private ctrmap.creativestudio.dialogs.Skel2CamSourcePanel camRollSource;
    private javax.swing.ButtonGroup camTgtBtnGroup;
    private javax.swing.JLabel camTgtLabel;
    private javax.swing.ButtonGroup convModeGroup;
    private javax.swing.JLabel convModeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private ctrmap.creativestudio.dialogs.Skel2CamSourcePanel posSource;
    private ctrmap.creativestudio.dialogs.Skel2CamSourcePanel tgtSource;
    // End of variables declaration//GEN-END:variables
}
