package ctrmap.editor.gui.editors.scenegraph.editors;

import ctrmap.renderer.scene.Camera;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.listeners.DocumentAdapterEx;
import javax.swing.event.DocumentEvent;

public class CameraEditor extends javax.swing.JPanel implements IScenegraphEditor {

	private Camera cam;

	public CameraEditor() {
		initComponents();	
		
		ComponentUtils.setNFValueClass(Float.class, near, far, fov);
		
		DocumentAdapterEx projectionUpdater = new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				if (cam != null){
					cam.zFar = ComponentUtils.getFloatFromDocument(far);
					cam.zNear = ComponentUtils.getFloatFromDocument(near);
					cam.FOV = ComponentUtils.getFloatFromDocument(fov);
				}
			}
		};
		far.getDocument().addDocumentListener(projectionUpdater);
		near.getDocument().addDocumentListener(projectionUpdater);
		fov.getDocument().addDocumentListener(projectionUpdater);
	}

	@Override
	public void load(Object o) {
		cam = null;
		if (o != null && o instanceof Camera) {
			Camera c = (Camera)o;
			name.setText(c.name);
			camType.setSelectedItem(c.mode.ordinal());
			tra.loadVec(c.translation);
			rot.loadVec(c.rotation);
			upVec.loadVec(c.lookAtUpVec);
			tgtVec.loadVec(c.lookAtTarget);
			far.setValue(c.zFar);
			near.setValue(c.zNear);
			fov.setValue(c.FOV);
			cam = c;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        transformPanel = new javax.swing.JPanel();
        tra = new xstandard.gui.components.Vec3fEditor();
        translationLabel = new javax.swing.JLabel();
        rotationLabel = new javax.swing.JLabel();
        rot = new xstandard.gui.components.Vec3fEditor();
        lookAtPanel = new javax.swing.JPanel();
        upVecLabel = new javax.swing.JLabel();
        upVec = new xstandard.gui.components.Vec3fEditor();
        tgtVec = new xstandard.gui.components.Vec3fEditor();
        tgtVecLabel = new javax.swing.JLabel();
        camModeLabel = new javax.swing.JLabel();
        camType = new javax.swing.JComboBox<>();
        projectionPanel = new javax.swing.JPanel();
        fovLabel = new javax.swing.JLabel();
        fov = new javax.swing.JFormattedTextField();
        nearLabel = new javax.swing.JLabel();
        near = new javax.swing.JFormattedTextField();
        farLabel = new javax.swing.JLabel();
        far = new javax.swing.JFormattedTextField();

        nameLabel.setText("Name:");

        name.setText("-");

        transformPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Transform"));

        translationLabel.setText("Translation:");

        rotationLabel.setText("Rotation:");

        javax.swing.GroupLayout transformPanelLayout = new javax.swing.GroupLayout(transformPanel);
        transformPanel.setLayout(transformPanelLayout);
        transformPanelLayout.setHorizontalGroup(
            transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transformPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(translationLabel)
                    .addComponent(tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotationLabel)
                    .addComponent(rot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        transformPanelLayout.setVerticalGroup(
            transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transformPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(translationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lookAtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("LookAt"));

        upVecLabel.setText("Up vector:");

        tgtVecLabel.setText("Target:");

        javax.swing.GroupLayout lookAtPanelLayout = new javax.swing.GroupLayout(lookAtPanel);
        lookAtPanel.setLayout(lookAtPanelLayout);
        lookAtPanelLayout.setHorizontalGroup(
            lookAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookAtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lookAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upVecLabel)
                    .addComponent(upVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgtVecLabel)
                    .addComponent(tgtVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lookAtPanelLayout.setVerticalGroup(
            lookAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lookAtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgtVecLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgtVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(upVecLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        camModeLabel.setText("Mode:");

        camType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perspective", "Orthogonal", "LookAt" }));
        camType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camTypeActionPerformed(evt);
            }
        });

        projectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Projection"));

        fovLabel.setText("FOV");

        fov.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        nearLabel.setText("Near");

        near.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        farLabel.setText("Far");

        far.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout projectionPanelLayout = new javax.swing.GroupLayout(projectionPanel);
        projectionPanel.setLayout(projectionPanelLayout);
        projectionPanelLayout.setHorizontalGroup(
            projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projectionPanelLayout.createSequentialGroup()
                        .addComponent(farLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(far, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projectionPanelLayout.createSequentialGroup()
                        .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nearLabel)
                            .addComponent(fovLabel))
                        .addGap(18, 18, 18)
                        .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fov, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(near, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectionPanelLayout.setVerticalGroup(
            projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fovLabel)
                    .addComponent(fov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nearLabel)
                    .addComponent(near, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farLabel)
                    .addComponent(far, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transformPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lookAtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(camModeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(camType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(projectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camModeLabel)
                    .addComponent(camType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transformPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookAtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void camTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camTypeActionPerformed
		if (cam != null){
			cam.mode = Camera.Mode.values()[camType.getSelectedIndex()];
		}
    }//GEN-LAST:event_camTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camModeLabel;
    private javax.swing.JComboBox<String> camType;
    private javax.swing.JFormattedTextField far;
    private javax.swing.JLabel farLabel;
    private javax.swing.JFormattedTextField fov;
    private javax.swing.JLabel fovLabel;
    private javax.swing.JPanel lookAtPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JFormattedTextField near;
    private javax.swing.JLabel nearLabel;
    private javax.swing.JPanel projectionPanel;
    private xstandard.gui.components.Vec3fEditor rot;
    private javax.swing.JLabel rotationLabel;
    private xstandard.gui.components.Vec3fEditor tgtVec;
    private javax.swing.JLabel tgtVecLabel;
    private xstandard.gui.components.Vec3fEditor tra;
    private javax.swing.JPanel transformPanel;
    private javax.swing.JLabel translationLabel;
    private xstandard.gui.components.Vec3fEditor upVec;
    private javax.swing.JLabel upVecLabel;
    // End of variables declaration//GEN-END:variables
}
