package ctrmap.editor.gui.editors.scenegraph.editors;

import ctrmap.renderer.scene.model.Joint;
import ctrmap.renderer.scene.model.Skeleton;

public class JointEditor extends javax.swing.JPanel implements IScenegraphEditor {

	private Joint joint;

	public JointEditor() {
		initComponents();	
	}

	@Override
	public void load(Object o) {
		joint = null;
		if (o != null && o instanceof Joint) {
			Joint j = (Joint)o;
			jntName.setText(j.name);
			pJntName.setText(j.parentName == null ? "-" : j.parentName);
			tra.loadVec(j.position);
			rot.loadVec(j.rotation);
			sca.loadVec(j.scale);
			ikRole.setSelectedIndex(j.kinematicsRole.ordinal());
			bbX.setSelected(j.isBBX());
			bbY.setSelected(j.isBBY());
			bbZ.setSelected(j.isBBZ());
			bbAim.setSelected(j.isBBAim());
			joint = j;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jntNameLabel = new javax.swing.JLabel();
        jntName = new javax.swing.JLabel();
        transformPanel = new javax.swing.JPanel();
        tra = new xstandard.gui.components.Vec3fEditor();
        traLabel = new javax.swing.JLabel();
        rotLabel = new javax.swing.JLabel();
        rot = new xstandard.gui.components.Vec3fEditor();
        scaLabel = new javax.swing.JLabel();
        sca = new xstandard.gui.components.Vec3fEditor();
        pJntNameLabel = new javax.swing.JLabel();
        pJntName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ikRoleLabel = new javax.swing.JLabel();
        ikRole = new javax.swing.JComboBox<>();
        billboardModeLabel = new javax.swing.JLabel();
        bbX = new javax.swing.JCheckBox();
        bbY = new javax.swing.JCheckBox();
        bbZ = new javax.swing.JCheckBox();
        bbAim = new javax.swing.JCheckBox();

        jntNameLabel.setText("Name:");

        jntName.setText("-");

        transformPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Transform"));

        traLabel.setText("Translation:");

        rotLabel.setText("Rotation:");

        scaLabel.setText("Scale:");

        javax.swing.GroupLayout transformPanelLayout = new javax.swing.GroupLayout(transformPanel);
        transformPanel.setLayout(transformPanelLayout);
        transformPanelLayout.setHorizontalGroup(
            transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transformPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traLabel)
                    .addComponent(tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotLabel)
                    .addComponent(rot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scaLabel)
                    .addComponent(sca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transformPanelLayout.setVerticalGroup(
            transformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transformPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(traLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pJntNameLabel.setText("Parent name:");

        pJntName.setText("-");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));

        ikRoleLabel.setText("IK role");

        ikRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Effector", "Joint", "Chain" }));
        ikRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikRoleActionPerformed(evt);
            }
        });

        billboardModeLabel.setText("Billboard:");

        bbX.setForeground(new java.awt.Color(255, 0, 0));
        bbX.setText("X");
        bbX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbXActionPerformed(evt);
            }
        });

        bbY.setForeground(new java.awt.Color(0, 153, 0));
        bbY.setText("Y");
        bbY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbYActionPerformed(evt);
            }
        });

        bbZ.setForeground(new java.awt.Color(0, 0, 255));
        bbZ.setText("Z");
        bbZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbZActionPerformed(evt);
            }
        });

        bbAim.setText("Aim");
        bbAim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbAimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bbX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbZ)
                        .addGap(50, 50, 50)
                        .addComponent(bbAim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ikRoleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ikRole, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(billboardModeLabel))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikRoleLabel)
                    .addComponent(ikRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(billboardModeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbX)
                    .addComponent(bbY)
                    .addComponent(bbZ)
                    .addComponent(bbAim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transformPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pJntNameLabel)
                            .addComponent(jntNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jntName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pJntName, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jntNameLabel)
                    .addComponent(jntName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pJntNameLabel)
                    .addComponent(pJntName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transformPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bbXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbXActionPerformed
		if (joint != null){
			joint.setBBX(bbX.isSelected());
		}
    }//GEN-LAST:event_bbXActionPerformed

    private void bbYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbYActionPerformed
        if (joint != null){
			joint.setBBY(bbY.isSelected());
		}
    }//GEN-LAST:event_bbYActionPerformed

    private void bbZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbZActionPerformed
        if (joint != null){
			joint.setBBZ(bbZ.isSelected());
		}
    }//GEN-LAST:event_bbZActionPerformed

    private void ikRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikRoleActionPerformed
		if (joint != null){
			joint.kinematicsRole = Skeleton.KinematicsRole.values()[ikRole.getSelectedIndex()];
		}
    }//GEN-LAST:event_ikRoleActionPerformed

    private void bbAimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbAimActionPerformed
		if (joint != null){
			joint.setBBAim(bbAim.isSelected());
		}
    }//GEN-LAST:event_bbAimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bbAim;
    private javax.swing.JCheckBox bbX;
    private javax.swing.JCheckBox bbY;
    private javax.swing.JCheckBox bbZ;
    private javax.swing.JLabel billboardModeLabel;
    private javax.swing.JComboBox<String> ikRole;
    private javax.swing.JLabel ikRoleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jntName;
    private javax.swing.JLabel jntNameLabel;
    private javax.swing.JLabel pJntName;
    private javax.swing.JLabel pJntNameLabel;
    private xstandard.gui.components.Vec3fEditor rot;
    private javax.swing.JLabel rotLabel;
    private xstandard.gui.components.Vec3fEditor sca;
    private javax.swing.JLabel scaLabel;
    private xstandard.gui.components.Vec3fEditor tra;
    private javax.swing.JLabel traLabel;
    private javax.swing.JPanel transformPanel;
    // End of variables declaration//GEN-END:variables
}
