package ctrmap.editor.gui.editors.scenegraph.editors;

import ctrmap.renderer.scene.Light;
import javax.swing.event.ChangeEvent;
import javax.swing.event.DocumentEvent;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.listeners.DocumentAdapterEx;

public
class LightEditor extends javax.swing.JPanel implements IScenegraphEditor {

	private Light light;
	
	public LightEditor() {
		initComponents();
		
		ComponentUtils.setNFValueClass(Float.class, posX, posY, posZ, dirX, dirY, dirZ);
		
		DocumentAdapterEx posUpdater = new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				if (light != null){
					light.position.x = ComponentUtils.getFloatFromDocument(posX);
					light.position.y = ComponentUtils.getFloatFromDocument(posY);
					light.position.z = ComponentUtils.getFloatFromDocument(posZ);
				}
			}
		};
		
		DocumentAdapterEx dirUpdater = new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				if (light != null){
					light.direction.x = ComponentUtils.getFloatFromDocument(dirX);
					light.direction.y = ComponentUtils.getFloatFromDocument(dirY);
					light.direction.z = ComponentUtils.getFloatFromDocument(dirZ);
				}
			}
		};
		
		ComponentUtils.addDocumentListenerToTFs(posUpdater, posX, posY, posZ);
		ComponentUtils.addDocumentListenerToTFs(dirUpdater, dirX, dirY, dirZ);
		
		setIndex.addChangeListener((ChangeEvent e) -> {
			if (light != null){
				light.setIndex = (Integer)setIndex.getValue();
			}
		});
	}
	
	public void load(Object o){
		light = null;
		if (o != null && o instanceof Light){
			Light l = (Light) o;
			setAmbColor.attachColor(l.ambientColor);
			setDifColor.attachColor(l.diffuseColor);
			setSpc0Color.attachColor(l.specular0Color);
			setSpc1Color.attachColor(l.specular1Color);
			setIndex.setValue(l.setIndex);
			lightName.setText(l.name);
			ComponentUtils.setTFsVector(l.position, posX, posY, posZ);
			ComponentUtils.setTFsVector(l.direction, dirX, dirY, dirZ);
			light = l;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lightNameLabel = new javax.swing.JLabel();
        lightName = new javax.swing.JLabel();
        generalPanel = new javax.swing.JPanel();
        setIndexLabel = new javax.swing.JLabel();
        setIndex = new javax.swing.JSpinner();
        lightPosLabel = new javax.swing.JLabel();
        posX = new javax.swing.JFormattedTextField();
        posY = new javax.swing.JFormattedTextField();
        posZ = new javax.swing.JFormattedTextField();
        lightDirLabel = new javax.swing.JLabel();
        dirX = new javax.swing.JFormattedTextField();
        dirY = new javax.swing.JFormattedTextField();
        dirZ = new javax.swing.JFormattedTextField();
        colorsPanel = new javax.swing.JPanel();
        colAmbLabel = new javax.swing.JLabel();
        setAmbColor = new xstandard.gui.components.SimpleColorSelector();
        setDifColor = new xstandard.gui.components.SimpleColorSelector();
        colDifLabel = new javax.swing.JLabel();
        setSpc0Color = new xstandard.gui.components.SimpleColorSelector();
        colSpc0Label = new javax.swing.JLabel();
        setSpc1Color = new xstandard.gui.components.SimpleColorSelector();
        colSpc1Label = new javax.swing.JLabel();

        lightNameLabel.setText("Light name:");

        lightName.setText("-");

        generalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        setIndexLabel.setText("Light set index");

        setIndex.setModel(new javax.swing.SpinnerNumberModel());

        lightPosLabel.setText("Position:");

        posX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        posY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        posZ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lightDirLabel.setText("Direction:");

        dirX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        dirY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        dirZ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(setIndexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lightPosLabel)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(posX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posZ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lightDirLabel)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(dirX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dirY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dirZ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setIndexLabel)
                    .addComponent(setIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lightPosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightDirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        colAmbLabel.setText("Ambient");

        colDifLabel.setText("Diffuse");

        colSpc0Label.setText("Specular 0");

        colSpc1Label.setText("Specular 1");

        javax.swing.GroupLayout colorsPanelLayout = new javax.swing.GroupLayout(colorsPanel);
        colorsPanel.setLayout(colorsPanelLayout);
        colorsPanelLayout.setHorizontalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colAmbLabel)
                    .addComponent(colDifLabel)
                    .addComponent(colSpc1Label)
                    .addComponent(colSpc0Label))
                .addGap(18, 18, 18)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setAmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setDifColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setSpc1Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setSpc0Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        colorsPanelLayout.setVerticalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(setAmbColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setDifColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setSpc0Color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setSpc1Color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, colorsPanelLayout.createSequentialGroup()
                        .addComponent(colAmbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colDifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colSpc0Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colSpc1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lightNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lightName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(colorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightNameLabel)
                    .addComponent(lightName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colAmbLabel;
    private javax.swing.JLabel colDifLabel;
    private javax.swing.JLabel colSpc0Label;
    private javax.swing.JLabel colSpc1Label;
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JFormattedTextField dirX;
    private javax.swing.JFormattedTextField dirY;
    private javax.swing.JFormattedTextField dirZ;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel lightDirLabel;
    private javax.swing.JLabel lightName;
    private javax.swing.JLabel lightNameLabel;
    private javax.swing.JLabel lightPosLabel;
    private javax.swing.JFormattedTextField posX;
    private javax.swing.JFormattedTextField posY;
    private javax.swing.JFormattedTextField posZ;
    private xstandard.gui.components.SimpleColorSelector setAmbColor;
    private xstandard.gui.components.SimpleColorSelector setDifColor;
    private javax.swing.JSpinner setIndex;
    private javax.swing.JLabel setIndexLabel;
    private xstandard.gui.components.SimpleColorSelector setSpc0Color;
    private xstandard.gui.components.SimpleColorSelector setSpc1Color;
    // End of variables declaration//GEN-END:variables
}
