package ctrmap.editor.gui.backuprestore;

import xstandard.fs.FSFile;
import xstandard.gui.components.NoSpaceFirstDocument;
import xstandard.gui.components.listeners.DocumentAdapterEx;
import xstandard.text.FormattingUtils;
import xstandard.text.StringEx;
import java.awt.Color;
import javax.swing.event.DocumentEvent;

public class BackupNameEntryDialog extends javax.swing.JDialog {

	private final FSFile backupRoot;
	
	private String result = null;
	
	public BackupNameEntryDialog(java.awt.Frame parent, boolean modal, FSFile backupRoot) {
		super(parent, modal);
		initComponents();
		this.backupRoot = backupRoot;
		
		backupNameField.setDocument(new NoSpaceFirstDocument());
		
		backupNameField.setText(FormattingUtils.getCommonFormattedDateForFileName());
		
		backupNameField.getDocument().addDocumentListener(new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				setConfirmButtonEnabledByPathValidity();
			}
		});
		
		setConfirmButtonEnabledByPathValidity();
		setLocationRelativeTo(parent);
	}
	
	public String getResult(){
		return result;
	}
	
	private void setConfirmButtonEnabledByPathValidity(){
		btnConfirm.setEnabled(checkFileNameValidSetWarn());
	}
	
	private boolean checkFileNameValidSetWarn() {
		String n = backupNameField.getText();
		hintLabel.setForeground(Color.BLACK);
		hintLabel.setText("");
		if (n == null || n.isEmpty()) {
			hintLabel.setText("Directory name can not be empty");
			return false;
		} else {
			char firstNonLetterOrDigit = StringEx.findFirstNonLetterOrDigit(n, '_', ' ', '-', '.');
			if (firstNonLetterOrDigit > 0) {
				hintLabel.setText("Directory name can not contain the character \"" + firstNonLetterOrDigit + "\"");
				return false;
			}

			if (backupRoot.getChild(n).exists()) {
				hintLabel.setText("Backup directory already exists.");
				return false;
			}
			
			return true;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backupNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup");
        setResizable(false);

        jLabel1.setText("Choose a name for the backup");

        btnConfirm.setText("Backup");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backupNameField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 233, Short.MAX_VALUE))
                    .addComponent(hintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backupNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		result = backupNameField.getText();
		dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField backupNameField;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
