package ctrmap.editor.gui.backuprestore;

import ctrmap.editor.system.workspace.backup.ProjectBackupConfig;

public class BackupEntry extends javax.swing.JPanel {

	public ProjectBackupConfig.BackupInfo backupInfo;
	private BackupRestoreForm form;
	
	public BackupEntry(ProjectBackupConfig.BackupInfo info, BackupRestoreForm form) {
		this.form = form;
		initComponents();
		this.backupInfo = info;
		nameLabel.setText(backupInfo.path + (info.automatic ? " (Automatic backup)" : ""));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        btnRestoreBackup = new javax.swing.JButton();
        btnDeleteBackup = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));
        setAlignmentY(0.0F);
        setLayout(new java.awt.BorderLayout());

        nameLabel.setText("Backup Name");
        add(nameLabel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setMinimumSize(new java.awt.Dimension(130, 15));
        buttonsPanel.setLayout(new java.awt.BorderLayout());

        btnRestoreBackup.setText("Restore");
        btnRestoreBackup.setPreferredSize(new java.awt.Dimension(70, 15));
        btnRestoreBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreBackupActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnRestoreBackup, java.awt.BorderLayout.CENTER);

        btnDeleteBackup.setText("Delete");
        btnDeleteBackup.setPreferredSize(new java.awt.Dimension(71, 15));
        btnDeleteBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBackupActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnDeleteBackup, java.awt.BorderLayout.LINE_END);

        add(buttonsPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBackupActionPerformed
		form.removeBackupEntryAction(this);
    }//GEN-LAST:event_btnDeleteBackupActionPerformed

    private void btnRestoreBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreBackupActionPerformed
		form.restoreBackupEntryAction(this);
    }//GEN-LAST:event_btnRestoreBackupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteBackup;
    private javax.swing.JButton btnRestoreBackup;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
