package ctrmap.editor.gui.backuprestore;

import ctrmap.editor.system.workspace.CTRMapProject;

public class InitialBackupRestoreDialog extends javax.swing.JDialog {

	public long result = 0;

	public InitialBackupRestoreDialog(java.awt.Frame parent, boolean modal, CTRMapProject project) {
		super(parent, modal);
		initComponents();
		periodSelector.setHourValue(4);
		setLocationRelativeTo(parent);
	}

	public long getResult() {
		return result;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JButton();
        periodSelector = new xstandard.gui.components.TimePeriodSelector();
        backupIntervalLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        screenTimeLabel = new javax.swing.JLabel();
        btnBackupEnable = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup and restore setup");
        setResizable(false);

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        backupIntervalLabel.setText("Backup interval:");

        descLabel.setText("<html>\n<u>Welcome!</u>\n<br/>\n<br/>\nCTRMap is a highly experimental tool. It is <i>not</i> out of the question that your project might often suffer some <i>very</i> minor cases of serious data corruption.\n<br/>\n<br/>\nHence, it is recommended that you enable CTRMap to periodically back up your workspace, should anything unexpected happen.\n</html>");

        screenTimeLabel.setText("of CTRMap screen time");

        btnBackupEnable.setSelected(true);
        btnBackupEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupEnableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackupEnable)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(screenTimeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backupIntervalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(periodSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBackupEnable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(periodSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupIntervalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screenTimeLabel)
                .addGap(23, 23, 23)
                .addComponent(btnConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackupEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupEnableActionPerformed
		periodSelector.setEnabled(btnBackupEnable.isSelected());
    }//GEN-LAST:event_btnBackupEnableActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		if (btnBackupEnable.isSelected()) {
			result = periodSelector.getSelectedMillisValue();
		} else {
			result = 0;
		}
		dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backupIntervalLabel;
    private javax.swing.JCheckBox btnBackupEnable;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel descLabel;
    private xstandard.gui.components.TimePeriodSelector periodSelector;
    private javax.swing.JLabel screenTimeLabel;
    // End of variables declaration//GEN-END:variables
}
