
package ctrmap.editor.system.script;

import ctrmap.pokescript.LangConstants;
import xstandard.fs.FSFile;
import xstandard.text.FormattingUtils;
import java.io.PrintStream;

/**
 *
 */
public class IncludeGeneratorCommons {
	public static void printHeader(PrintStream stream, String header){
		stream.println("/**=================================================");
		stream.println("*");
		stream.println("*   " + header);
		stream.println("*");
		stream.print  ("*   Rev. ");
		stream.println(FormattingUtils.getCommonFormattedDate());
		stream.println("*   This file was auto-generated by CTRMap.");
		stream.println("*");
		stream.println("===================================================*/");
	}
	
	public static void appendInt(PrintStream stream, String name, int value){
		stream.print("static final int ");
		stream.print(name);
		stream.print(" = ");
		stream.print(value);
		stream.println(";");
	}
	
	public static FSFile ensureClass(FSFile incRoot, String packageName, String className) {
		FSFile pkg = incRoot.getChild(packageName);
		pkg.mkdir();
		return pkg.getChild(className + LangConstants.LANG_GENERAL_HEADER_EXTENSION);
	}
}
