package ctrmap.creativestudio.editors;

import ctrmap.creativestudio.ngcs.tree.CSNode;
import ctrmap.renderer.scene.Light;
import xstandard.gui.components.VectorEditorListener;
import xstandard.gui.components.listeners.DocumentAdapterEx;
import xstandard.math.vec.RGBA;
import xstandard.math.vec.Vec3f;
import javax.swing.event.DocumentEvent;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.SimpleColorSelector;

public class LightEditor extends javax.swing.JPanel implements IEditor {

	/**
	 * Creates new form LightEditor
	 */
	public LightEditor() {
		initComponents();
		
		lightDirEditor.addListener(new VectorEditorListener() {
			@Override
			public void onChanged() {
				Vec3f vec = lightDirEditor.getVector();
				lightDirVectorPreview.setText(String.format("(%.3f; %.3f; %.3f)", vec.x, vec.y, vec.z));
			}
		});

		lightSetIndex.getDocument().addDocumentListener(new DocumentAdapterEx() {
			@Override
			public void textChangedUpdate(DocumentEvent e) {
				if (light != null) {
					light.setIndex = ComponentUtils.getIntFromDocument(lightSetIndex, light.setIndex);
				}
			}
		});

		lightColorEditor.addListener(new VectorEditorListener() {
			@Override
			public void onChanged() {
				RGBA color = lightColorEditor.getVecAsColor();
				btnSetLightColor.attachColor(color);
				saveLightColor(color);
			}
		});
		
		btnSetLightColor.setCallback(new SimpleColorSelector.ColorSelectionCallback() {
			@Override
			public void colorSelected(RGBA color) {
				lightColorEditor.loadVec(color.toVector4().toVec3());
				lightColorEditor.refresh();
				saveLightColor(color);
			}
		});
		
		lightColorType.addActionListener(((e) -> {
			showLightColor();
		}));
		
		lightType.addActionListener(((e) -> {
			if (light != null) {
				light.directional = lightType.getSelectedIndex() == 0;
			}
		}));
	}

	private CSNode node;
	private Light light;

	private RGBA getCurrentLightColor() {
		if (light != null) {
			int type = lightColorType.getSelectedIndex();
			switch (type) {
				case 0:
					return light.ambientColor;
				case 1:
					return light.diffuseColor;
				case 2:
					return light.specular0Color;
				case 3:
					return light.specular1Color;
			}
		}
		return new RGBA();
	}
	
	private void saveLightColor(RGBA color) {
		if (light != null) {
			getCurrentLightColor().set(color);
		}
	}

	@Override
	public void handleObject(Object o) {
		if (IEditor.checkIsCompatibleNG(o, Light.class)) {
			node = (CSNode) o;
			light = (Light) node.getContent();
		} else {
			node = null;
			light = null;
		}
		nameTextField1.loadNode(node);
		if (light == null) {
			lightPos.loadVec(null);
			lightDirEditor.loadVec(null);
			lightSetIndex.setValue(0f);
			lightType.setSelectedIndex(0);
		} else {
			lightPos.loadVec(light.position);
			lightDirEditor.loadVec(light.direction);
			lightSetIndex.setValue(light.setIndex);
			lightType.setSelectedIndex(light.directional ? 0 : 1);
		}
		showLightColor();
	}
	
	private void showLightColor() {
		RGBA color = getCurrentLightColor();
		lightColorEditor.loadVec(color.toVector4().toVec3());
		btnSetLightColor.attachColor(color);
	}

	@Override
	public void save() {
		//everything is auto-saved
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lightColorPanel = new javax.swing.JPanel();
        lightColorEditor = new xstandard.gui.components.NormalizedVec3fSliderEditor();
        lightColorType = new javax.swing.JComboBox<>();
        btnSetLightColor = new xstandard.gui.components.SimpleColorSelector();
        lightDirPanel = new javax.swing.JPanel();
        lightDirEditor = new xstandard.gui.components.DirectionalVec3fSliderEditor();
        lightDirVectorLabel = new javax.swing.JLabel();
        lightDirVectorPreview = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTextField1 = new ctrmap.creativestudio.editors.NameTextField();
        jLabel2 = new javax.swing.JLabel();
        lightSetIndex = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        lightType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lightPos = new xstandard.gui.components.Vec3fEditor();

        lightColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Light colors"));

        lightColorEditor.setRGBLabels(true);

        lightColorType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambient", "Diffuse", "Specular 0", "Specular 1" }));

        javax.swing.GroupLayout lightColorPanelLayout = new javax.swing.GroupLayout(lightColorPanel);
        lightColorPanel.setLayout(lightColorPanelLayout);
        lightColorPanelLayout.setHorizontalGroup(
            lightColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lightColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightColorEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(lightColorPanelLayout.createSequentialGroup()
                        .addComponent(lightColorType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSetLightColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        lightColorPanelLayout.setVerticalGroup(
            lightColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lightColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lightColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSetLightColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightColorType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lightColorEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lightDirPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Light direction"));

        lightDirVectorLabel.setText("Direction vector:");

        lightDirVectorPreview.setText("-");

        javax.swing.GroupLayout lightDirPanelLayout = new javax.swing.GroupLayout(lightDirPanel);
        lightDirPanel.setLayout(lightDirPanelLayout);
        lightDirPanelLayout.setHorizontalGroup(
            lightDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lightDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightDirEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(lightDirPanelLayout.createSequentialGroup()
                        .addComponent(lightDirVectorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightDirVectorPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lightDirPanelLayout.setVerticalGroup(
            lightDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightDirEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lightDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightDirVectorLabel)
                    .addComponent(lightDirVectorPreview))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel1.setText("Name");

        jLabel2.setText("Light set index");

        lightSetIndex.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setText("Type");

        lightType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directional", "Positional" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightSetIndex))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lightType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightSetIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Light position"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightColorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightDirPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightDirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xstandard.gui.components.SimpleColorSelector btnSetLightColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private xstandard.gui.components.NormalizedVec3fSliderEditor lightColorEditor;
    private javax.swing.JPanel lightColorPanel;
    private javax.swing.JComboBox<String> lightColorType;
    private xstandard.gui.components.DirectionalVec3fSliderEditor lightDirEditor;
    private javax.swing.JPanel lightDirPanel;
    private javax.swing.JLabel lightDirVectorLabel;
    private javax.swing.JLabel lightDirVectorPreview;
    private xstandard.gui.components.Vec3fEditor lightPos;
    private javax.swing.JFormattedTextField lightSetIndex;
    private javax.swing.JComboBox<String> lightType;
    private ctrmap.creativestudio.editors.NameTextField nameTextField1;
    // End of variables declaration//GEN-END:variables
}
