package ctrmap.editor.gui.settings;

import ctrmap.CTRMapResources;
import ctrmap.editor.CTRMap;
import ctrmap.editor.system.workspace.CTRMapProject;
import xstandard.formats.msgtxt.MsgTxt;

public class EditorSettingsPanel extends javax.swing.JPanel implements SettingsPanel {

	public static final MsgTxt EDITOR_SETTINGS_RES = new MsgTxt(CTRMapResources.ACCESSOR.getStream("message/editor_settings_res.msgtxt"));
	private static final String DESC_ENABLE_MONS_EDIT = "enable_pokemon_editing_desc";

	public static final String PRJFLAG_IS_UNSAFE_MODE = "UnsafeMode";
	public static final String PRJFLAG_IS_MONSEDIT_ENABLE = "EnableMonsEdit";

	private SettingsForm parent;

	public EditorSettingsPanel() {
		initComponents();
	}

	@Override
	public void attachParent(SettingsForm parent) {
		this.parent = parent;

		SettingsPanel.batchAddMouseOverListener(this, DESC_ENABLE_MONS_EDIT, btnEnableMonsEdit);
		loadSettings(parent.cm);
	}

	public void loadSettings(CTRMap cm) {
		btnEnableMonsEdit.setSelected(cm.getProject().getFlag(PRJFLAG_IS_MONSEDIT_ENABLE));
	}

	public void save() {
		//auto saved
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnableMonsEdit = new javax.swing.JCheckBox();
        capsLabel = new javax.swing.JLabel();

        btnEnableMonsEdit.setText("Enable Pokémon editing");
        btnEnableMonsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableMonsEditActionPerformed(evt);
            }
        });

        capsLabel.setText("Capabilities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnableMonsEdit)
                    .addComponent(capsLabel))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(capsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnableMonsEdit)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableMonsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableMonsEditActionPerformed
		boolean setMonsEditFlag = false;
		CTRMapProject p = parent.cm.getProject();
		boolean v = btnEnableMonsEdit.isSelected();
		if (v) {
			if (parent.cm.getProject().getFlag(PRJFLAG_IS_UNSAFE_MODE)) {
				setMonsEditFlag = true;
			} else {
				MonsEditToggleDialog dlg = new MonsEditToggleDialog(parent, true);
				dlg.setVisible(true);
				if (dlg.getResult()) {
					setMonsEditFlag = true;
					parent.cm.getProject().setFlag(PRJFLAG_IS_UNSAFE_MODE, true);
				} else {
					btnEnableMonsEdit.setSelected(false);
				}
			}
		} else {
			setMonsEditFlag = true;
		}
		if (setMonsEditFlag) {
			parent.cm.broadcastGlobalEvent(CTRMap.GEVENT_FLAG_CHANGE_ID, PRJFLAG_IS_MONSEDIT_ENABLE, v);
			p.setFlag(PRJFLAG_IS_MONSEDIT_ENABLE, v);
			p.saveProjectData();
		}
    }//GEN-LAST:event_btnEnableMonsEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnEnableMonsEdit;
    private javax.swing.JLabel capsLabel;
    // End of variables declaration//GEN-END:variables

	@Override
	public MsgTxt getMsgTxt() {
		return EDITOR_SETTINGS_RES;
	}

	@Override
	public SettingsForm getParentForm() {
		return parent;
	}
}
