package ctrmap.editor.gui.settings;

import ctrmap.editor.CTRMap;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.DefaultCaret;

public class SettingsForm extends javax.swing.JFrame {

	public static boolean GLOBAL_SETTINGS_PANEL_LOCK = false;
	public static SettingsForm LOCKED_INSTANCE = null;

	public CTRMap cm;

	private final List<SettingsPanel> panels = new ArrayList<>();

	private SettingsForm(CTRMap ctrmap) {
		GLOBAL_SETTINGS_PANEL_LOCK = true;
		LOCKED_INSTANCE = this;
		initComponents();
		panels.add(gfxSettings);
		panels.add(audioSettings);
		for (SettingsPanel p : ctrmap.getEditorManager().getSettingsPanels()) {
			panels.add(p);
			settingsTabbedPane.addTab(p.getTitle(), (Component) p);
		}
		cm = ctrmap;
		((DefaultCaret) descArea.getCaret()).setUpdatePolicy(DefaultCaret.NEVER_UPDATE);

		setSubformAttachment(this);
	}

	public static void open(CTRMap cm) {
		if (!GLOBAL_SETTINGS_PANEL_LOCK) {
			new SettingsForm(cm).setVisible(true);
		} else {
			LOCKED_INSTANCE.toFront();
		}
	}

	private void setSubformAttachment(Component c) {
		if (c instanceof SettingsPanel) {
			((SettingsPanel) c).attachParent(this);
		}
		if (c instanceof Container) {
			for (Component sub : ((Container) c).getComponents()) {
				setSubformAttachment(sub);
			}
		}
	}

	public void showHint(SettingsPanel pnl, String resId) {
		descArea.setText(pnl.getMsgTxt().getLineForName(resId));
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTabbedPane = new javax.swing.JTabbedPane();
        gfxSettings = new ctrmap.editor.gui.settings.GfxSettingsPanel();
        audioSettings = new ctrmap.editor.gui.settings.AudioSettingsForm();
        hintSP = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CTRMap settings");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        settingsTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                settingsTabbedPaneStateChanged(evt);
            }
        });
        settingsTabbedPane.addTab("Video", gfxSettings);
        settingsTabbedPane.addTab("Audio", audioSettings);

        descArea.setColumns(20);
        descArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descArea.setLineWrap(true);
        descArea.setRows(5);
        descArea.setWrapStyleWord(true);
        hintSP.setViewportView(descArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintSP, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(settingsTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(settingsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintSP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		for (SettingsPanel p : panels) {
			p.save();
		}
		GLOBAL_SETTINGS_PANEL_LOCK = false;
		LOCKED_INSTANCE = null;
    }//GEN-LAST:event_formWindowClosing

    private void settingsTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_settingsTabbedPaneStateChanged
		descArea.setText(null);
    }//GEN-LAST:event_settingsTabbedPaneStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ctrmap.editor.gui.settings.AudioSettingsForm audioSettings;
    private javax.swing.JTextArea descArea;
    private ctrmap.editor.gui.settings.GfxSettingsPanel gfxSettings;
    private javax.swing.JScrollPane hintSP;
    private javax.swing.JTabbedPane settingsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
